### ISSUE TITLE
Dificuldades com Android Synthetic

### ISSUE THREAD

**Issue by LuizCarlosComZ** [nglauber/dominando_android3#1]
Ola Glauber.

Sou novo no ambient de programação. Estou dando meus primeiros passos através de ser livro.
Estou com dificuldade de atualizar os códigos tendo em vista que parece que o Android Synthetic foi descontinuado.
Voce poderia indicar uma maneira de compilar seus códigos de maneira mais atual?
Estou usando a versão 2022.3.1 Patch 3 do android Studio.

Segue:
HotelDetailsFragments.kt
"import kotlinx.android.synthetic.main.fragment_hotel_details.*"

No aguardo,

**Comment by nglauber** [comment]
Oi Luiz. O livro foi lançado em 2019 e muita coisa mudou de lá pra cá. 
Particularmente para o synthetic, você pode utilizar View Binding. Você pode encontrar a documentação sobre o assunto aqui:
https://developer.android.com/topic/libraries/view-binding/migration?hl=pt-br
Mas sinceramente, aconselho você a dar uma olhada no Jetpack Compose, que é o framework de UI para Android recomendado pelo Google.
https://developer.android.com/jetpack/compose

**Comment by LuizCarlosComZ** [comment]
Olá Glauber.
Obrigado pelo retorno rápido!

Estou parado no capítulo 8, tentando resolver está incompatibilidade para
continuar com o estudo.

É difícil acompanhar a rapidez exponencial da tecnologia.

Mas o livro ainda está a venda e acredito que muitos que se aventuram em
programação (como eu) devem compra-lo como apoio nos primeiros acessos.
Portanto, acredito que seria muito importante deixar algo documentado no
seu perfil no GitHub para este seu de leitor.

Acredito ser relevante e importante na avaliação de sua publicação.

Saudações,

Luiz Carlos, por celular.

Em sex., 22 de dez. de 2023 20:52, Nelson Glauber ***@***.***>
escreveu:

**Comment by nglauber** [comment]
Oi Luiz. Desculpa a demora em responder, mas tirei um recesso entre o natal e o ano-novo e só agora estou resolvendo as pendências... Já conseguiu progredir nos estudos? Caso não tenha, compartilha teu código que assim que puder dou uma olhada.

**Comment by LuizCarlosComZ** [comment]
Olá Nelson Glauber.
Obrigado pelo retorno.

Como estou começando, ainda não define o projeto para iniciar com os
códigos.

Estou na fase de conhecimentos e entendimento processo de programação para
entender se tenho aptidões para seguir com o desenvolvimento de um
aplicativo para o segmento METALMECÂNICO da  indústria de usinagem.

Estou acompanhando um outro livro, kotlin em Ação.

Assim que acabar a leitura e prática, estou pensando em contratar um desses
cursos online para evoluir na prática e aprofundar com os estudos.

Meu objetivo é desenvolvimento de aplicativos.

Caso você ministre algum curso do tipo ou puder sugerir algum, serei muito
grato pela indicação.

A dica sobre o compose foi ótima, ajudou enormemente!

Saudações e sucesso.

Luiz Carlos, por celular.

Em qua., 3 de jan. de 2024, 21:49, Nelson Glauber ***@***.***>
escreveu:
